/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package camel.training

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication

@SpringBootApplication
class App {
	static void main(String[] args) {
		SpringApplication.run(App, args)	
	}
}
